#!/usr/bin/env python3
from __future__ import annotations
import hashlib
import json
from _bootstrap import PROJECT_ROOT
from mtare_topo.governance import load_json,write_json
RUN_ID="gate3_20260828_gse_route_token_failure_attribution_v1_seed0";CARD=PROJECT_ROOT/"configs/v3/gate3/data_cards/gse_route_token_failure_attribution_v1.json";SPEC=PROJECT_ROOT/"configs/v3/gate3/gse_route_token_failure_attribution_v1.json";PYTHON="/home/zeng-workstation/.local/share/mtare_topo_comm/envs/phase3_torch290_cu129_zarr2187_v1/bin/python"
def sha(p):
 h=hashlib.sha256()
 with p.open("rb") as f:
  for b in iter(lambda:f.read(4*1024*1024),b""):h.update(b)
 return h.hexdigest()
def main():
 if CARD.exists() or SPEC.exists():raise RuntimeError("route-token-attribution card/spec exists")
 base=load_json(PROJECT_ROOT/"configs/v3/gate3/data_cards/gse_low_support_endpoint_observability_audit_v1.json");approval={"status":"APPROVED","approved_by":"user-standing-authorization","approved_at":"2026-08-28T00:00:00+08:00","authorized_gates":[3],"authorized_operations":["audit"],"scope":"One immutable zero-training C01-C08 token/Teacher failure attribution over the sealed residual outputs and objective graphs; no C09/C10/M-TARE.","confirmation_reference":"User instructed automatic best-choice execution without routine approval prompts."}
 card=dict(base);card.update({"card_id":"gse_route_token_failure_attribution_v1","title":"GSE route token and exclusive-Teacher failure attribution","status":"APPROVED_FOR_ONE_IMMUTABLE_GSE_ROUTE_TOKEN_FAILURE_ATTRIBUTION_V1","approval":approval,"purpose":"Decide whether the failed low-dimensional route residual lost exit relations or was trained against a mutually exclusive objective event that one causal LiDAR scene cannot uniquely support.","methods":{"main":"Join the two low-support endpoint failures to raw three-seed exit flow, trained per-seed outputs and directly adjacent objective graph events. Classify a stable junction decision next to a sensor-range-scale junction as exclusive-Teacher conflict; classify large seed structural spread despite unanimous route-stop evidence as representation instability. No fitting or threshold selection.","baseline":"The sealed 643-parameter route residual improved ordinary episodes but recovered zero of two low-support endpoints and regressed graph node recall.","fallback":"If both failures are not uniquely attributable, stop and inspect full token metrics without designing a new model. If any exclusive-Teacher conflict exists, build a spatial multi-event Teacher before another head; otherwise test a full-token relation head."},"acceptance":{"population":"Exactly 188126 C01-C08 observations, 98 relation endpoints in 40 endpoint-bearing worlds, two low-support selection terminals and four Teacher rows.","provenance":"Every endpoint resolves to its frozen objective graph node; all route outputs and stable global identities match.","attribution":"Both low-support failures receive one frozen mechanism; at least one exclusive-Teacher conflict and one seed-representation instability are reproduced.","isolation":"Zero optimizer, inference, threshold selection, C09, C10 and M-TARE reads."},"estimated_cost":{"compute":"CPU joins and vectorization over frozen arrays plus 40 small objective graphs; no model inference or optimization.","wall_time_hours":0.05,"host_ram_gb":3,"gpu_memory_gb":0,"disk_gb":0.05,"gpu":"none"}});write_json(CARD,card)
 action="results/gate3_semantics/gate3_20260828_gse_action_set_node_training_v1_seed0";support="results/gate3_semantics/gate3_20260828_gse_development_relation_endpoint_support_audit_v1_seed0";observe="results/gate3_semantics/gate3_20260828_gse_low_support_endpoint_observability_audit_v1_seed0";flow="results/gate3_semantics/gate3_20260828_gse_route_conditioned_exit_flow_audit_v1_seed0";route="results/gate3_semantics/gate3_20260828_gse_route_conditioned_event_residual_training_v1_seed0";graphs="results/gate0_baseline/gate0_20260811_cano_100_topology_parent_candidate_audit_v2_bounded_resampling_seed0/artifacts/candidates";cache=f"{action}/scratch/action_set_cache";inputs=[f"{cache}/raw_tokens.npy",f"{cache}/history_references.npy",f"{cache}/history_mask.npy",f"{cache}/identity.npy",f"{cache}/partition_code.npy",f"{cache}/global_sequence_index.npy",f"{cache}/manifest.json",f"{support}/artifacts/audit/endpoint_support_audit.jsonl",f"{support}/artifacts/evidence_sha256.txt",f"{observe}/RUN_STATE.json",f"{observe}/artifacts/evidence_sha256.txt",f"{observe}/artifacts/audit/low_selection_rows.json",f"{flow}/RUN_STATE.json",f"{flow}/artifacts/evidence_sha256.txt",f"{flow}/artifacts/audit/endpoint_flow.jsonl",f"{route}/RUN_STATE.json",f"{route}/artifacts/evidence_sha256.txt",f"{route}/metrics/summary.json"]
 endpoint_path=PROJECT_ROOT/f"{support}/artifacts/audit/endpoint_support_audit.jsonl";worlds=sorted({json.loads(line)["world"] for line in endpoint_path.read_text().splitlines() if line.strip()})
 if len(worlds)!=40:raise RuntimeError("route-token-attribution endpoint world count drift")
 inputs.extend([f"{graphs}/{world}/graph.json" for world in worlds])
 inputs.extend([f"{route}/artifacts/models/seed{seed}/all_outputs.npz" for seed in range(3)])
 tools={"data_card":str(CARD.relative_to(PROJECT_ROOT)),"route_model":"src/mtare_topo/representation/gse_route_conditioned_event_residual.py","executor":"tools/v3/execute_gse_route_token_failure_attribution_v1.py","runner":"tools/v3/run_gse_route_token_failure_attribution_v1.py","freezer":"tools/v3/freeze_gse_route_token_failure_attribution_spec_v1.py","tests":"tests/v3/unit/test_gse_route_token_failure_attribution.py","governance":"src/mtare_topo/governance.py","preflight":"tools/v3/preflight.py","create_run":"tools/v3/create_run.py"}
 spec={"schema_version":"v3_run_spec_v1","gate":3,"execution_phase":3,"date":"20260828","slug":"gse_route_token_failure_attribution_v1","seed":0,"operation":"audit","question":"Did the low-dimensional route residual fail because it compressed exit relations, or because exclusive objective terminal/junction semantics are not uniquely observable?","method":card["methods"]["main"],"baseline":card["methods"]["baseline"],"fallback":card["methods"]["fallback"],"data_card":str(CARD.relative_to(PROJECT_ROOT)),"config_path":str(CARD.relative_to(PROJECT_ROOT)),"user_authorization":approval,"acceptance_criteria":list(card["acceptance"].values()),"expected_counts":{"development_worlds":80,"endpoint_worlds":40,"observations":188126,"relation_endpoints":98,"low_selection_endpoints":2,"low_selection_rows":4,"optimizer_steps":0,"model_inference_frames":0,"c09_worlds_read":0,"c10_worlds_read":0,"mtare_worlds_read":0},"expected_evidence":["98 endpoint adjacency records, exact two-endpoint/four-row base-versus-corrected token attribution, mechanism summary, PNG/PDF/SVG/source, logs, RUN_STATE and SHA-256 seal."],"estimated_cost":card["estimated_cost"],"frozen_inputs":{p:sha(PROJECT_ROOT/p) for p in sorted(set(inputs))},"frozen_tools":{n:{"path":p,"sha256":sha(PROJECT_ROOT/p)} for n,p in tools.items()},"working_directory":str(PROJECT_ROOT),"command":["/usr/bin/timeout","300s",PYTHON,"tools/v3/run_gse_route_token_failure_attribution_v1.py","--spec",str(SPEC),"--run-dir",str(PROJECT_ROOT/f"results/gate3_semantics/{RUN_ID}")]};write_json(SPEC,spec);print(CARD.relative_to(PROJECT_ROOT));print(SPEC.relative_to(PROJECT_ROOT));return 0
if __name__=="__main__":raise SystemExit(main())
