#!/usr/bin/env python3
from __future__ import annotations
import hashlib
from _bootstrap import PROJECT_ROOT
from mtare_topo.governance import write_json
RUN_ID="gate3_20260829_gse_soft_angular_peak_hard_negative_readiness_v1_seed0";SPEC=PROJECT_ROOT/"configs/v3/gate3/gse_soft_angular_peak_hard_negative_readiness_v1.json";CARD="configs/v3/gate3/data_cards/gse_soft_angular_peak_hard_negative_readiness_v1.json";PYTHON="/home/zeng-workstation/.local/share/mtare_topo_comm/envs/phase3_torch290_cu129_zarr2187_v1/bin/python"
def sha(path):
 d=hashlib.sha256()
 with path.open("rb") as f:
  for b in iter(lambda:f.read(4*1024*1024),b""):d.update(b)
 return d.hexdigest()
def main():
 if SPEC.exists():raise RuntimeError("V2 readiness spec exists")
 ds="results/gate2_representation/gate2_20260824_gse_deduplicated_dataset_export_v1_seed0";teacher="results/gate2_representation/gate2_20260829_gse_circular_exit_geometry_field_teacher_export_v1_seed0";v1="results/gate3_semantics/gate3_20260829_gse_circular_peak_geometry_three_seed_training_v1_seed0"
 inputs=[CARD,f"{ds}/RUN_STATE.json",f"{ds}/artifacts/shard_manifest.json",f"{ds}/artifacts/evidence_sha256.txt",f"{teacher}/RUN_STATE.json",f"{teacher}/artifacts/export/teacher_shard_manifest.jsonl",f"{teacher}/artifacts/evidence_sha256.txt",f"{v1}/RUN_STATE.json",f"{v1}/metrics/summary.json",f"{v1}/artifacts/evidence_sha256.txt"]
 for s in range(3):
  inputs.append(f"{v1}/artifacts/models/seed{s}/best.pt")
  for p in sorted((PROJECT_ROOT/v1/f"artifacts/models/seed{s}/development_predictions").glob("*.npz")):inputs.append(str(p.relative_to(PROJECT_ROOT)))
 tools={"model":"src/mtare_topo/representation/gse_circular_peak_geometry_model.py","loss":"src/mtare_topo/representation/gse_soft_angular_peak_loss.py","metrics":"src/mtare_topo/evaluation/gse_circular_peak_metrics.py","executor":"tools/v3/execute_gse_soft_angular_peak_hard_negative_readiness_v1.py","runner":"tools/v3/run_gse_soft_angular_peak_hard_negative_readiness_v1.py","freezer":"tools/v3/freeze_gse_soft_angular_peak_hard_negative_readiness_spec_v1.py","real_batch":"tools/v3/execute_gse_circular_peak_geometry_model_readiness_v1.py","tests":"tests/v3/unit/test_gse_soft_angular_peak_loss.py","governance":"src/mtare_topo/governance.py","preflight":"tools/v3/preflight.py","create_run":"tools/v3/create_run.py"}
 spec={"schema_version":"v3_run_spec_v1","gate":3,"execution_phase":3,"date":"20260829","slug":"gse_soft_angular_peak_hard_negative_readiness_v1","seed":0,"operation":"audit","data_card":CARD,"question":"Does V1 fail from hard single-bin/high-confidence ghost peaks, and can one soft-angular plus hard-negative loss directly correct that failure on all frozen backbones without training?","method":"Frozen C07/C08 angular/NMS attribution plus C07-derived radius-4 circular focal heatmap and equal-count top hard-negative ranking synthetic/real backward.","baseline":"V1 exact-bin equal-mass BCE and decode-only top4/NMS upper bounds.","fallback":"Any failed reproduction, ordering, gradient, rotation or real backward stops V2.","user_authorization":{"status":"APPROVED","approved_by":"user-standing-authorization","approved_at":"2026-08-29T06:20:00+08:00","authorized_gates":[3],"authorized_operations":["audit"],"scope":"One immutable zero-training V1 attribution/V2 loss readiness.","confirmation_reference":"User delegated continuous best-method execution."},"acceptance_criteria":["Reproduce V1 exact AP; C07 +-10-degree AP>=0.89 and offset p90=4 bins; decode-only <=16 degrees remains insufficient.","Soft target rotation exact with unit centers and radius-4 bounded support.","Correct loss < shifted < far and < ghost; ghost/center gradient signs suppress/promote.","All three frozen backbones have finite eight-row V2 backward and suppressing top-hard-negative gradients.","Zero optimizer/checkpoint/test/graph/planner and source unchanged."],"expected_counts":{"c07_observations":21548,"c08_observations":24394,"c07_peaks":45504,"c08_peaks":51537,"real_rows":8,"frozen_seeds":3,"support_radius_bins":4,"optimizer_steps":0,"c09_worlds_read":0,"c10_worlds_read":0,"mtare_worlds_read":0,"graph_replays":0},"expected_evidence":["Tolerance/offset/NMS attribution CSV and summary.","Synthetic loss/gradient and all-seed real backward evidence.","PNG/PDF/SVG/source, environment, log, RUN_STATE and seal."],"estimated_cost":{"compute":"CPU frozen-output attribution and three real backward passes","wall_time_hours":0.1,"host_ram_gb":6,"gpu_memory_gb":0,"disk_gb":0.1,"gpu":"none"},"frozen_inputs":{p:sha(PROJECT_ROOT/p) for p in sorted(inputs)},"frozen_tools":{n:{"path":p,"sha256":sha(PROJECT_ROOT/p)} for n,p in tools.items()},"working_directory":str(PROJECT_ROOT),"command":["/usr/bin/timeout","1800s",PYTHON,"tools/v3/run_gse_soft_angular_peak_hard_negative_readiness_v1.py","--spec",str(SPEC),"--run-dir",str(PROJECT_ROOT/f"results/gate3_semantics/{RUN_ID}")]}
 write_json(SPEC,spec);print(SPEC.relative_to(PROJECT_ROOT));return 0
if __name__=="__main__":raise SystemExit(main())
