#!/usr/bin/env python3
from __future__ import annotations
import hashlib
from _bootstrap import PROJECT_ROOT
from mtare_topo.governance import load_json,write_json
RUN_ID="gate3_20260828_gse_route_conditioned_exit_flow_audit_v1_seed0";CARD=PROJECT_ROOT/"configs/v3/gate3/data_cards/gse_route_conditioned_exit_flow_audit_v1.json";SPEC=PROJECT_ROOT/"configs/v3/gate3/gse_route_conditioned_exit_flow_audit_v1.json";PYTHON="/home/zeng-workstation/.local/share/mtare_topo_comm/envs/phase3_torch290_cu129_zarr2187_v1/bin/python"
def sha(p):
 h=hashlib.sha256()
 with p.open("rb") as f:
  for b in iter(lambda:f.read(4*1024*1024),b""):h.update(b)
 return h.hexdigest()
def main():
 if CARD.exists() or SPEC.exists():raise RuntimeError("route-flow card/spec exists")
 base=load_json(PROJECT_ROOT/"configs/v3/gate3/data_cards/gse_low_support_endpoint_observability_audit_v1.json");approval={"status":"APPROVED","approved_by":"user-standing-authorization","approved_at":"2026-08-28T00:00:00+08:00","authorized_gates":[3],"authorized_operations":["audit"],"scope":"One immutable zero-training C01-C08 route-conditioned exit-flow audit; no C09/C10/M-TARE.","confirmation_reference":"User instructed automatic best-choice execution."}
 card=dict(base);card.update({"card_id":"gse_route_conditioned_exit_flow_audit_v1","title":"GSE route-conditioned exit-flow observability audit","status":"APPROVED_FOR_ONE_IMMUTABLE_GSE_ROUTE_CONDITIONED_EXIT_FLOW_AUDIT_V1","approval":approval,"purpose":"Test whether incoming-direction-conditioned exit flow separates terminal from junction identities before training a route-conditioned event head.","methods":{"main":"Fixed physical score mean_seed((backward-forward)/(forward+backward+lateral)), maximum over each endpoint Teacher window; no learned weights or selected threshold.","baseline":"Route-agnostic ActionSetNodeDetector failure mechanisms from the sealed observability audit.","fallback":"If fit or selection AUC <0.80, stop route-conditioned head design."},"acceptance":{"population":"188126 observations and 98 relation endpoints.","fit":"C01-C06 terminal-vs-junction identity AUC >=0.80.","selection":"C07-C08 AUC >=0.80, terminal mean above junction, and at least one low-support terminal above the fit junction median."},"estimated_cost":{"compute":"CPU vectorization over the sealed raw token cache; no model inference or optimization.","wall_time_hours":0.05,"host_ram_gb":2,"gpu_memory_gb":0,"disk_gb":0.05,"gpu":"none"}});write_json(CARD,card)
 action="results/gate3_semantics/gate3_20260828_gse_action_set_node_training_v1_seed0";support="results/gate3_semantics/gate3_20260828_gse_development_relation_endpoint_support_audit_v1_seed0";observe="results/gate3_semantics/gate3_20260828_gse_low_support_endpoint_observability_audit_v1_seed0";inputs=[f"{action}/scratch/action_set_cache/raw_tokens.npy",f"{action}/scratch/action_set_cache/identity.npy",f"{action}/scratch/action_set_cache/partition_code.npy",f"{action}/scratch/action_set_cache/manifest.json",f"{support}/artifacts/audit/endpoint_support_audit.jsonl",f"{support}/artifacts/evidence_sha256.txt",f"{observe}/RUN_STATE.json",f"{observe}/artifacts/evidence_sha256.txt",f"{observe}/artifacts/audit/summary.json"]
 tools={"data_card":str(CARD.relative_to(PROJECT_ROOT)),"executor":"tools/v3/execute_gse_route_conditioned_exit_flow_audit_v1.py","runner":"tools/v3/run_gse_route_conditioned_exit_flow_audit_v1.py","freezer":"tools/v3/freeze_gse_route_conditioned_exit_flow_audit_spec_v1.py","tests":"tests/v3/unit/test_gse_route_conditioned_exit_flow.py","governance":"src/mtare_topo/governance.py","preflight":"tools/v3/preflight.py","create_run":"tools/v3/create_run.py"}
 spec={"schema_version":"v3_run_spec_v1","gate":3,"execution_phase":3,"date":"20260828","slug":"gse_route_conditioned_exit_flow_audit_v1","seed":0,"operation":"audit","question":"Does a fixed incoming-direction-conditioned exit-flow score separate terminal from junction identities across development splits?","method":card["methods"]["main"],"baseline":card["methods"]["baseline"],"fallback":card["methods"]["fallback"],"data_card":str(CARD.relative_to(PROJECT_ROOT)),"config_path":str(CARD.relative_to(PROJECT_ROOT)),"user_authorization":approval,"acceptance_criteria":list(card["acceptance"].values()),"expected_counts":{"development_worlds":80,"observations":188126,"relation_endpoints":98,"optimizer_steps":0,"model_inference_frames":0,"c09_worlds_read":0,"c10_worlds_read":0,"mtare_worlds_read":0},"expected_evidence":["98 endpoint flow records, split AUC/means, low-support ranks, PNG/PDF/SVG/source, logs, RUN_STATE and seal."],"estimated_cost":card["estimated_cost"],"frozen_inputs":{p:sha(PROJECT_ROOT/p) for p in inputs},"frozen_tools":{n:{"path":p,"sha256":sha(PROJECT_ROOT/p)} for n,p in tools.items()},"working_directory":str(PROJECT_ROOT),"command":["/usr/bin/timeout","300s",PYTHON,"tools/v3/run_gse_route_conditioned_exit_flow_audit_v1.py","--spec",str(SPEC),"--run-dir",str(PROJECT_ROOT/f"results/gate3_semantics/{RUN_ID}")]};write_json(SPEC,spec);print(CARD.relative_to(PROJECT_ROOT));print(SPEC.relative_to(PROJECT_ROOT));return 0
if __name__=="__main__":raise SystemExit(main())
