#!/usr/bin/env python3
from __future__ import annotations
import hashlib
from _bootstrap import PROJECT_ROOT
from mtare_topo.governance import write_json
RUN_ID="gate3_20260828_gse_spatial_event_set_readiness_v1_seed0";SPEC=PROJECT_ROOT/"configs/v3/gate3/gse_spatial_event_set_readiness_v1.json";PYTHON="/home/zeng-workstation/.local/share/mtare_topo_comm/envs/phase3_torch290_cu129_zarr2187_v1/bin/python"
def sha(p):
 h=hashlib.sha256()
 with p.open("rb") as f:
  for b in iter(lambda:f.read(4*1024*1024),b""):h.update(b)
 return h.hexdigest()
def main():
 if SPEC.exists():raise RuntimeError("readiness spec exists")
 teacher="results/gate2_representation/gate2_20260828_gse_spatial_multi_event_teacher_export_v1_seed0";source="results/gate2_representation/gate2_20260824_gse_deduplicated_dataset_export_v1_seed0";inputs=[f"{teacher}/RUN_STATE.json",f"{teacher}/metrics/summary.json",f"{teacher}/artifacts/evidence_sha256.txt",f"{teacher}/artifacts/export/summary.json",f"{teacher}/artifacts/export/teacher_shard_manifest.jsonl",f"{source}/RUN_STATE.json",f"{source}/artifacts/evidence_sha256.txt",f"{source}/artifacts/shard_manifest.json"]
 tools={"model":"src/mtare_topo/representation/gse_spatial_event_set.py","teacher_interface":"src/mtare_topo/teacher/gse_spatial_multi_event_teacher.py","executor":"tools/v3/execute_gse_spatial_event_set_readiness_v1.py","runner":"tools/v3/run_gse_spatial_event_set_readiness_v1.py","freezer":"tools/v3/freeze_gse_spatial_event_set_readiness_spec_v1.py","tests":"tests/v3/unit/test_gse_spatial_event_set.py","governance":"src/mtare_topo/governance.py","preflight":"tools/v3/preflight.py","create_run":"tools/v3/create_run.py"}
 approval={"status":"APPROVED","approved_by":"user-standing-authorization","approved_at":"2026-08-28T00:00:00+08:00","authorized_gates":[3],"authorized_operations":["audit"],"scope":"One immutable zero-training C01-C08 Teacher-join and decoder readiness audit; no scans, C09/C10/M-TARE or trained inference.","confirmation_reference":"User instructed automatic best-choice execution without routine approval prompts."}
 spec={"schema_version":"v3_run_spec_v1","gate":3,"execution_phase":3,"date":"20260828","slug":"gse_spatial_event_set_readiness_v1","seed":0,"operation":"audit","question":"Does the 16-query spatial event decoder satisfy the full exported Teacher join, set matching, circular equivariance and finite-gradient contracts before training?","method":"Validate all 80 Teacher shards against source global identities, then run a deterministic random-initialized decoder on real cardinality 0-5 targets and audit matching, permutation, rotation and backward stability.","baseline":"Old exclusive scene classifier has no multi-event relative-position interface.","fallback":"Stop before training and fix only typed interface/loss defects; do not alter Teacher, data or acceptance gates.","user_authorization":approval,"acceptance_criteria":["Exact 80 worlds, 188126 rows, 133055 tokens and frozen type/cardinality distributions.","Exact source join, padding, range, identity uniqueness and distance/identity order.","93638 parameters, real cardinalities 0-5, query permutation loss <=1e-6, circular rotation error <=5e-4m and finite backward.","Zero optimization, trained inference, C09/C10/M-TARE reads."],"expected_counts":{"worlds":80,"observations":188126,"tokens":133055,"parameters":93638,"optimizer_steps":0,"c09_worlds_read":0,"c10_worlds_read":0,"mtare_worlds_read":0},"expected_evidence":["Full 80-shard audit log, readiness summary, RUN_STATE and SHA-256 seal."],"estimated_cost":{"compute":"CPU Zarr target validation and one six-sample random decoder forward/backward; no scan or trained model inference.","wall_time_hours":0.05,"host_ram_gb":2,"gpu_memory_gb":0,"disk_gb":0.01,"gpu":"none"},"frozen_inputs":{p:sha(PROJECT_ROOT/p) for p in sorted(inputs)},"frozen_tools":{n:{"path":p,"sha256":sha(PROJECT_ROOT/p)} for n,p in tools.items()},"working_directory":str(PROJECT_ROOT),"command":["/usr/bin/timeout","360s",PYTHON,"tools/v3/run_gse_spatial_event_set_readiness_v1.py","--spec",str(SPEC),"--run-dir",str(PROJECT_ROOT/f"results/gate3_semantics/{RUN_ID}")]};write_json(SPEC,spec);print(SPEC.relative_to(PROJECT_ROOT));return 0
if __name__=="__main__":raise SystemExit(main())
