#!/usr/bin/env python3
from __future__ import annotations
import hashlib
from _bootstrap import PROJECT_ROOT
from mtare_topo.governance import write_json
RUN_ID="gate3_20260829_gse_cardinality_conditioned_circular_slot_transport_readiness_v1r_seed0";SPEC=PROJECT_ROOT/"configs/v3/gate3/gse_cardinality_conditioned_circular_slot_transport_readiness_v1r.json";CARD="configs/v3/gate3/data_cards/gse_cardinality_conditioned_circular_slot_transport_readiness_v1r.json";PYTHON="/home/zeng-workstation/.local/share/mtare_topo_comm/envs/phase3_torch290_cu129_zarr2187_v1/bin/python"
def sha(path):
 d=hashlib.sha256()
 with path.open("rb") as stream:
  for block in iter(lambda:stream.read(4*1024*1024),b""):d.update(block)
 return d.hexdigest()
def main():
 if SPEC.exists():raise RuntimeError("slot readiness V1R spec exists")
 dataset="results/gate2_representation/gate2_20260824_gse_deduplicated_dataset_export_v1_seed0";teacher="results/gate2_representation/gate2_20260829_gse_circular_exit_geometry_field_teacher_export_v1_seed0";attribution="results/gate3_semantics/gate3_20260829_gse_circular_exit_set_process_failure_attribution_v1_seed0";v1="results/gate3_semantics/gate3_20260829_gse_cardinality_conditioned_circular_slot_transport_readiness_v1_seed0"
 inputs=[CARD,f"{dataset}/RUN_STATE.json",f"{dataset}/artifacts/evidence_sha256.txt",f"{dataset}/artifacts/shard_manifest.json",f"{teacher}/RUN_STATE.json",f"{teacher}/artifacts/evidence_sha256.txt",f"{teacher}/artifacts/export/teacher_shard_manifest.jsonl",f"{attribution}/RUN_STATE.json",f"{attribution}/artifacts/evidence_sha256.txt",f"{attribution}/artifacts/attribution/summary.json",f"{v1}/RUN_STATE.json",f"{v1}/metrics/summary.json",f"{v1}/artifacts/evidence_sha256.txt"]
 tools={"model":"src/mtare_topo/representation/gse_cardinality_conditioned_circular_slot_transport.py","executor":"tools/v3/execute_gse_cardinality_conditioned_circular_slot_transport_readiness_v1.py","runner":"tools/v3/run_gse_cardinality_conditioned_circular_slot_transport_readiness_v1.py","freezer":"tools/v3/freeze_gse_cardinality_conditioned_circular_slot_transport_readiness_spec_v1r.py","real_batch":"tools/v3/execute_gse_circular_peak_geometry_model_readiness_v1.py","model_tests":"tests/v3/unit/test_gse_cardinality_conditioned_circular_slot_transport.py","readiness_tests":"tests/v3/unit/test_gse_cardinality_conditioned_circular_slot_transport_readiness.py","governance":"src/mtare_topo/governance.py","preflight":"tools/v3/preflight.py","create_run":"tools/v3/create_run.py"}
 spec={"schema_version":"v3_run_spec_v1","gate":3,"execution_phase":3,"date":"20260829","slug":"gse_cardinality_conditioned_circular_slot_transport_readiness_v1r","seed":0,"operation":"audit","data_card":CARD,"data_card_status":"APPROVED_FOR_ONE_IMMUTABLE_GSE_CARDINALITY_CONDITIONED_CIRCULAR_SLOT_TRANSPORT_READINESS_V1R","question":"Does the unchanged slot-transport contract pass after the boolean audit metric is repaired?","method":"Exact V1 readiness with boolean valid-mask mismatch measured logically rather than by unsupported subtraction.","baseline":"Immutable V1 system failure before scientific result.","fallback":"Any remaining system or scientific failure stops the decoder.","user_authorization":{"status":"APPROVED","approved_by":"user-standing-authorization","approved_at":"2026-08-28T22:20:00+08:00","authorized_gates":[3],"authorized_operations":["audit"],"scope":"One immutable V1R boolean-metric repair.","confirmation_reference":"User delegated continuous best-method execution without repeated approval prompts."},"acceptance_criteria":["Dedicated boolean comparison regression passes; no other scientific change.","Exact full population and no forbidden Teacher arrays.","Bijection, duplicate gradient, concentration and real finite backward pass.","Circular/resultant, slot/batch permutation and repeat <=3e-5; zero forbidden operations."],"expected_counts":{"worlds":80,"observations":188126,"peaks":396913,"cardinality_1":7525,"cardinality_2":154279,"cardinality_3":24458,"cardinality_4":1864,"real_rows":8,"optimizer_steps":0,"c09_worlds_read":0,"c10_worlds_read":0,"mtare_worlds_read":0,"graph_replays":0},"expected_evidence":["V1 failure binding and boolean regression.","Same population, synthetic and real readiness evidence.","PNG/PDF/SVG/source, environment, log, RUN_STATE and seal."],"estimated_cost":{"compute":"CPU same V1 readiness","wall_time_hours":0.1,"host_ram_gb":6,"gpu_memory_gb":0,"disk_gb":0.1,"gpu":"none"},"frozen_inputs":{path:sha(PROJECT_ROOT/path) for path in sorted(inputs)},"frozen_tools":{name:{"path":path,"sha256":sha(PROJECT_ROOT/path)} for name,path in tools.items()},"working_directory":str(PROJECT_ROOT),"command":["/usr/bin/timeout","1800s",PYTHON,"tools/v3/run_gse_cardinality_conditioned_circular_slot_transport_readiness_v1.py","--spec",str(SPEC),"--run-dir",str(PROJECT_ROOT/f"results/gate3_semantics/{RUN_ID}")]}
 write_json(SPEC,spec);print(SPEC.relative_to(PROJECT_ROOT));return 0
if __name__=="__main__":raise SystemExit(main())
