#!/usr/bin/env python3
"""Freeze Data Card and run spec for the low-support observability audit."""
from __future__ import annotations
import hashlib
from _bootstrap import PROJECT_ROOT
from mtare_topo.governance import load_json,write_json

RUN_ID="gate3_20260828_gse_low_support_endpoint_observability_audit_v1_seed0";CARD=PROJECT_ROOT/"configs/v3/gate3/data_cards/gse_low_support_endpoint_observability_audit_v1.json";SPEC=PROJECT_ROOT/"configs/v3/gate3/gse_low_support_endpoint_observability_audit_v1.json";PYTHON="/home/zeng-workstation/.local/share/mtare_topo_comm/envs/phase3_torch290_cu129_zarr2187_v1/bin/python"
def _sha(path):
 h=hashlib.sha256()
 with path.open("rb") as f:
  for b in iter(lambda:f.read(4*1024*1024),b""):h.update(b)
 return h.hexdigest()
def main():
 if CARD.exists() or SPEC.exists():raise RuntimeError("observability card/spec exists; overwrite forbidden")
 base=load_json(PROJECT_ROOT/"configs/v3/gate3/data_cards/gse_action_set_node_training_v1.json");approval={"status":"APPROVED","approved_by":"user-standing-authorization","approved_at":"2026-08-28T00:00:00+08:00","authorized_gates":[3],"authorized_operations":["audit"],"scope":"One immutable C01-C08 low-support endpoint observability audit with frozen three-seed inference; no optimization, C09, C10 or M-TARE.","confirmation_reference":"User instructed automatic best-choice execution without routine approval prompts."}
 source=dict(base["source"]);source["raw_sources"]=list(source["raw_sources"])+["Sealed relation-endpoint support audit and scientific-FAIL identity-residual run; only C01-C08 development identities are diagnosed."]
 sampling=dict(base["sampling"]);sampling.update({"effective_structure_event_count":98,"structure_event_counts":{"relation_endpoints":98,"fit_low_support_endpoints":10,"selection_low_support_endpoints":2},"rule":"Use all sealed C01-C08 observations at 1 m spacing and their exact past-only five-frame histories. Nearest-neighbor reference statistics use C01-C06 only; C07-C08 supplies diagnostic queries, not fitted weights or thresholds."})
 split=dict(base["split"]);split.update({"checkpoint_and_threshold_selection":"No checkpoint or threshold selection. C07-C08 is diagnostic query data only; fixed deployment threshold remains 0.97.","future_validation":"C09 is forbidden because it was already used by the predecessor model and contributes zero audit inputs.","historical_pollution_audit":"All audit inputs are explicit C01-C08 cache/checkpoints/support evidence. C09/C10/M-TARE paths are absent.","world_disjoint":True,"trajectory_disjoint":True})
 card={"schema_version":"v3_data_card_v1","card_id":"gse_low_support_endpoint_observability_audit_v1","title":"GSE low-support relation-endpoint observability audit","status":"APPROVED_FOR_ONE_IMMUTABLE_GSE_LOW_SUPPORT_ENDPOINT_OBSERVABILITY_AUDIT_V1","purpose":"Distinguish structural proposal failure from junction/terminal class failure before selecting another model correction.","approval":approval,"source":source,"worlds":base["worlds"],"trajectories":base["trajectories"],"sampling":sampling,"split":split,"teacher":base["teacher"],"leakage_audit":base["leakage_audit"],"methods":{"main":"Frozen three-seed ActionSetNodeDetector inference plus deterministic fit-standardized 1/5-nearest-neighbor analysis in causal-context and physical exit-geometry spaces. No learned diagnostic probe.","baseline":"The sealed endpoint-support stages and fixed 0.97 action ensemble.","fallback":"If evidence is incomplete, seal FAIL and stop. Do not train, tune the threshold, or infer from C09/C10."},"acceptance":{"population":"188126 observations, 98 relation endpoints, 10 fit and 2 selection low-support endpoints.","evidence":"All three seeds, four low-selection rows, structural/conditional probabilities and context/geometry neighbors are present.","decision":"The audit must determine whether structural-only correction is excluded by at least one accepted but event-misclassified low-support endpoint."},"estimated_cost":{"compute":"Three frozen forward passes over 188126 cached observations plus deterministic nearest-neighbor diagnostics.","wall_time_hours":0.2,"host_ram_gb":4,"gpu_memory_gb":2,"disk_gb":0.1,"gpu":"one RTX 5090 D"},"retention":"Keep endpoint outcomes, four-row detailed diagnostics, summary, PNG/PDF/SVG/source, logs, environment, RUN_STATE and seal.","failure_policy":"Any source/environment/count/nonfinite/leakage/program failure seals FAIL. No changed-science retry."};write_json(CARD,card)
 action="results/gate3_semantics/gate3_20260828_gse_action_set_node_training_v1_seed0";cache=f"{action}/scratch/action_set_cache";support="results/gate3_semantics/gate3_20260828_gse_development_relation_endpoint_support_audit_v1_seed0";residual="results/gate3_semantics/gate3_20260828_gse_endpoint_identity_residual_training_v1r3_seed0";inputs=[f"{action}/RUN_STATE.json",f"{action}/artifacts/evidence_sha256.txt",f"{cache}/manifest.json",f"{cache}/raw_tokens.npy",f"{cache}/history_references.npy",f"{cache}/history_mask.npy",f"{cache}/normalization_mean.npy",f"{cache}/normalization_scale.npy",f"{cache}/partition_code.npy",f"{cache}/decision_target.npy",f"{cache}/decision_episode_id.npy",f"{cache}/identity.npy",f"{cache}/traversal_id.npy",f"{cache}/sequence_index.npy",f"{cache}/global_sequence_index.npy",f"{support}/RUN_STATE.json",f"{support}/artifacts/evidence_sha256.txt",f"{support}/artifacts/audit/endpoint_support_audit.jsonl",f"{residual}/RUN_STATE.json",f"{residual}/artifacts/evidence_sha256.txt",f"{residual}/metrics/summary.json"]+[f"{action}/artifacts/models/seed{s}/best.pt" for s in range(3)]
 tools={"data_card":str(CARD.relative_to(PROJECT_ROOT)),"executor":"tools/v3/execute_gse_low_support_endpoint_observability_audit_v1.py","runner":"tools/v3/run_gse_low_support_endpoint_observability_audit_v1.py","freezer":"tools/v3/freeze_gse_low_support_endpoint_observability_spec_v1.py","action_model":"src/mtare_topo/representation/gse_action_set_node.py","dataset":"src/mtare_topo/data/gse_action_set_cache.py","tests":"tests/v3/unit/test_gse_low_support_endpoint_observability.py","governance":"src/mtare_topo/governance.py","preflight":"tools/v3/preflight.py","create_run":"tools/v3/create_run.py"}
 spec={"schema_version":"v3_run_spec_v1","gate":3,"execution_phase":3,"date":"20260828","slug":"gse_low_support_endpoint_observability_audit_v1","seed":0,"operation":"audit","question":"Do rare relation endpoints fail because the structure is not observed or because an observed structure is assigned the wrong event class?","method":card["methods"]["main"],"baseline":card["methods"]["baseline"],"fallback":card["methods"]["fallback"],"data_card":str(CARD.relative_to(PROJECT_ROOT)),"config_path":str(CARD.relative_to(PROJECT_ROOT)),"user_authorization":approval,"acceptance_criteria":list(card["acceptance"].values()),"expected_counts":{"development_worlds":80,"observations":188126,"relation_endpoints":98,"fit_low_support_endpoints":10,"selection_low_support_endpoints":2,"model_inference_frames":564378,"optimizer_steps":0,"c09_worlds_read":0,"c10_worlds_read":0,"mtare_worlds_read":0},"expected_evidence":["98 endpoint outcomes; detailed four-row rare selection diagnostics; context/geometry neighbors; summary and paper figure; logs, RUN_STATE and seal."],"estimated_cost":card["estimated_cost"],"frozen_inputs":{p:_sha(PROJECT_ROOT/p) for p in sorted(set(inputs))},"frozen_tools":{n:{"path":p,"sha256":_sha(PROJECT_ROOT/p)} for n,p in tools.items()},"working_directory":str(PROJECT_ROOT),"command":["/usr/bin/systemd-inhibit","--what=sleep:shutdown","--why=GSE low-support endpoint observability audit","--mode=block","/usr/bin/timeout","--signal=INT","--kill-after=120s","900s",PYTHON,"tools/v3/run_gse_low_support_endpoint_observability_audit_v1.py","--spec",str(SPEC),"--run-dir",str(PROJECT_ROOT/f"results/gate3_semantics/{RUN_ID}")]};write_json(SPEC,spec);print(CARD.relative_to(PROJECT_ROOT));print(SPEC.relative_to(PROJECT_ROOT));return 0
if __name__=="__main__":raise SystemExit(main())
