#!/usr/bin/env python3
from __future__ import annotations
import hashlib
from _bootstrap import PROJECT_ROOT
from mtare_topo.governance import write_json
RUN_ID="gate3_20260829_gse_circular_exit_set_process_failure_attribution_v1_seed0";SPEC=PROJECT_ROOT/"configs/v3/gate3/gse_circular_exit_set_process_failure_attribution_v1.json";CARD="configs/v3/gate3/data_cards/gse_circular_exit_set_process_failure_attribution_v1.json";PYTHON="/home/zeng-workstation/.local/share/mtare_topo_comm/envs/phase3_torch290_cu129_zarr2187_v1/bin/python"
def sha(path):
 d=hashlib.sha256()
 with path.open("rb") as stream:
  for block in iter(lambda:stream.read(4*1024*1024),b""):d.update(block)
 return d.hexdigest()
def main():
 if SPEC.exists():raise RuntimeError("attribution spec exists")
 teacher="results/gate2_representation/gate2_20260829_gse_circular_exit_geometry_field_teacher_export_v1_seed0";training="results/gate3_semantics/gate3_20260829_gse_circular_exit_set_process_three_seed_training_v1_seed0"
 inputs=[CARD,f"{teacher}/RUN_STATE.json",f"{teacher}/artifacts/evidence_sha256.txt",f"{teacher}/artifacts/export/teacher_shard_manifest.jsonl",f"{training}/RUN_STATE.json",f"{training}/metrics/summary.json",f"{training}/artifacts/evidence_sha256.txt"]
 for seed in range(3):
  for path in sorted((PROJECT_ROOT/training/f"artifacts/models/seed{seed}/development_predictions").glob("*.npz")):inputs.append(str(path.relative_to(PROJECT_ROOT)))
 tools={"executor":"tools/v3/execute_gse_circular_exit_set_process_failure_attribution_v1.py","runner":"tools/v3/run_gse_circular_exit_set_process_failure_attribution_v1.py","freezer":"tools/v3/freeze_gse_circular_exit_set_process_failure_attribution_spec_v1.py","tests":"tests/v3/unit/test_gse_circular_exit_set_process_failure_attribution.py","governance":"src/mtare_topo/governance.py","preflight":"tools/v3/preflight.py","create_run":"tools/v3/create_run.py"}
 spec={"schema_version":"v3_run_spec_v1","gate":3,"execution_phase":3,"date":"20260829","slug":"gse_circular_exit_set_process_failure_attribution_v1","seed":0,"operation":"audit","data_card":CARD,"question":"Is the near-zero safe exit-set recall caused by localization capacity or by confidence separability?","method":"Frozen C07/C08 full-population circular assignment, tolerance/cardinality/residual attribution, and C07-to-C08 transfer of ten fixed confidence features.","baseline":"Exact formal two-degree original-score selection from the sealed failed run.","fallback":"Any population, reproduction, monotonicity, finite-score or attribution failure stops without a corrective.","user_authorization":{"status":"APPROVED","approved_by":"user-standing-authorization","approved_at":"2026-08-28T22:00:00+08:00","authorized_gates":[3],"authorized_operations":["audit"],"scope":"One immutable zero-training frozen-output attribution.","confirmation_reference":"User delegated continuous best-method execution without repeated approval prompts."},"acceptance_criteria":["Reproduce exact C07/C08 population and raw cardinality accuracy.","Report monotone 2/4/6/8/10/15/20-degree exit and exact-set curves without changing the formal two-degree contract.","Select every diagnostic confidence threshold on C07 only and transfer unchanged to C08 at row precision>=0.995.","Resolve localization versus confidence failure from predeclared evidence and keep all forbidden operations zero."],"expected_counts":{"c07_observations":21548,"c08_observations":24394,"c07_peaks":45504,"c08_peaks":51537,"frozen_seeds":3,"confidence_features":10,"bearing_tolerances":7,"optimizer_steps":0,"model_inference_observations":0,"c09_worlds_read":0,"c10_worlds_read":0,"mtare_worlds_read":0,"graph_replays":0},"expected_evidence":["Tolerance and cardinality-stratified metrics.","Confidence AP/safe C07 threshold/C08 transfer table.","Selected-bin, bin-center and oracle-bin residual errors.","PNG/PDF/SVG/source, environment, raw log, RUN_STATE and seal."],"estimated_cost":{"compute":"CPU-only frozen NumPy/Zarr attribution","wall_time_hours":0.1,"host_ram_gb":4,"gpu_memory_gb":0,"disk_gb":0.1,"gpu":"none"},"frozen_inputs":{path:sha(PROJECT_ROOT/path) for path in sorted(inputs)},"frozen_tools":{name:{"path":path,"sha256":sha(PROJECT_ROOT/path)} for name,path in tools.items()},"working_directory":str(PROJECT_ROOT),"command":["/usr/bin/timeout","1800s",PYTHON,"tools/v3/run_gse_circular_exit_set_process_failure_attribution_v1.py","--spec",str(SPEC),"--run-dir",str(PROJECT_ROOT/f"results/gate3_semantics/{RUN_ID}")]}
 write_json(SPEC,spec);print(SPEC.relative_to(PROJECT_ROOT));return 0
if __name__=="__main__":raise SystemExit(main())
