#!/usr/bin/env python3
"""Freeze the relation-endpoint episode-exposure audit."""
from __future__ import annotations
import hashlib
from _bootstrap import PROJECT_ROOT
from mtare_topo.governance import write_json
RUN_ID="gate3_20260828_gse_relation_endpoint_episode_exposure_audit_v1_seed0";CARD=PROJECT_ROOT/"configs/v3/gate3/data_cards/gse_relation_endpoint_episode_exposure_audit_v1.json";SPEC=PROJECT_ROOT/"configs/v3/gate3/gse_relation_endpoint_episode_exposure_audit_v1.json";PYTHON="/home/zeng-workstation/.local/share/mtare_topo_comm/envs/phase3_torch290_cu129_zarr2187_v1/bin/python"
def _sha(path):
 h=hashlib.sha256()
 with path.open("rb") as f:
  for b in iter(lambda:f.read(4*1024*1024),b""):h.update(b)
 return h.hexdigest()
def main():
 if CARD.exists() or SPEC.exists():raise RuntimeError("episode-exposure card/spec exists; overwrite forbidden")
 action="results/gate3_semantics/gate3_20260828_gse_action_set_node_training_v1_seed0";support="results/gate3_semantics/gate3_20260828_gse_development_relation_endpoint_support_audit_v1_seed0"
 approval={"status":"APPROVED","approved_by":"user-standing-authorization","approved_at":"2026-08-28T00:00:00+08:00","authorized_gates":[3],"authorized_operations":["audit"],"scope":"One immutable read-only C01-C08 episode-exposure audit; zero training, inference, C09/C10/M-TARE.","confirmation_reference":"User instructed automatic best-choice execution without routine approval prompts."}
 card={"schema_version":"v3_data_card_v1","card_id":"gse_relation_endpoint_episode_exposure_audit_v1","title":"GSE relation-endpoint identity episode-exposure audit","status":"APPROVED_FOR_ONE_IMMUTABLE_GSE_RELATION_ENDPOINT_EPISODE_EXPOSURE_AUDIT_V1","purpose":"Check whether the existing episode-preserving MIL still weights structure identities in proportion to their number of episodes.","approval":approval,"source":{"action_cache_run":action,"endpoint_support_audit":support,"license_or_allowed_use":"Local project-generated data and trained outputs."},"worlds":{"fit":"C01-C06 (60)","selection":"C07-C08 (20)","forbidden":"C09/C10/M-TARE"},"trajectories":{"rule":"No new trajectories; read exact cached episode IDs."},"sampling":{"raw_frame_count":252430,"effective_sample_count":188126,"independent_units":"98 distinct relation-endpoint identities: fit72, selection26.","positive_episodes":"Expected fit286 and selection110 among all 3282/1136 decision episodes."},"split":{"fit":"C01-C06","selection":"C07-C08 direction check","validation":"C09 unread","strict_test":"C10 unread"},"teacher":{"source":"Existing cached decision episode, event and identity arrays.","use":"Counting only; never student input."},"methods":{"main":"Count unique positive MIL episodes per relation-endpoint identity and aggregate by the pre-frozen 1-3/4-10/11-30/31+ support bins.","baseline":"Existing EpisodePreservingBatchSampler and episode-level MIL loss.","fallback":"If exposure is already identity-balanced, reject the corrective and do not train."},"acceptance":{"population":"Exactly 188126 observations, 98 endpoint identities, fit286 and selection110 endpoint episodes, all-decision episodes 3282/1136.","decision":"Corrective justified only if every fit low-support endpoint contributes one episode, fit high/low mean exposure ratio>=6, and selection does not reverse.","isolation":"Zero optimizer/model/inference/C09/C10/M-TARE."},"estimated_cost":{"compute":"CPU array count and plot","wall_time_hours":0.02,"host_ram_gb":1,"gpu_memory_gb":0,"disk_gb":0.05,"gpu":"none"},"retention":"Keep identity table, CSV, summary, PNG/PDF/SVG/source, logs and seal.","failure_policy":"Any hash/count mismatch fails closed."}
 write_json(CARD,card)
 cache=f"{action}/scratch/action_set_cache";inputs=[f"{action}/RUN_STATE.json",f"{action}/artifacts/evidence_sha256.txt",f"{cache}/manifest.json",f"{cache}/partition_code.npy",f"{cache}/identity.npy",f"{cache}/decision_episode_id.npy",f"{cache}/decision_target.npy",f"{support}/RUN_STATE.json",f"{support}/artifacts/evidence_sha256.txt",f"{support}/artifacts/audit/endpoint_support_audit.jsonl"]
 tools={"data_card":str(CARD.relative_to(PROJECT_ROOT)),"executor":"tools/v3/execute_gse_relation_endpoint_episode_exposure_audit_v1.py","runner":"tools/v3/run_gse_relation_endpoint_episode_exposure_audit_v1.py","freezer":"tools/v3/freeze_gse_relation_endpoint_episode_exposure_audit_spec_v1.py","sampler":"src/mtare_topo/data/gse_causal_episode_sampler.py","model_loss":"src/mtare_topo/representation/gse_action_set_node.py","governance":"src/mtare_topo/governance.py","preflight":"tools/v3/preflight.py","create_run":"tools/v3/create_run.py"}
 spec={"schema_version":"v3_run_spec_v1","gate":3,"execution_phase":3,"date":"20260828","slug":"gse_relation_endpoint_episode_exposure_audit_v1","seed":0,"operation":"audit","question":"Does episode-balanced MIL still overweight high-support structure identities?","method":card["methods"]["main"],"baseline":card["methods"]["baseline"],"fallback":card["methods"]["fallback"],"data_card":str(CARD.relative_to(PROJECT_ROOT)),"config_path":str(CARD.relative_to(PROJECT_ROOT)),"user_authorization":approval,"acceptance_criteria":list(card["acceptance"].values()),"expected_counts":{"development_worlds":80,"causal_observations":188126,"relation_endpoints":98,"fit_endpoint_episodes":286,"selection_endpoint_episodes":110,"model_inference_frames":0,"optimizer_steps":0,"model_updates":0,"c09_worlds_read":0,"c10_worlds_read":0,"mtare_worlds_read":0},"expected_evidence":["98-row identity exposure table, support-bin CSV, summary, PNG/PDF/SVG/source, logs and SHA-256 seal."],"estimated_cost":card["estimated_cost"],"frozen_inputs":{p:_sha(PROJECT_ROOT/p) for p in inputs},"frozen_tools":{n:{"path":p,"sha256":_sha(PROJECT_ROOT/p)} for n,p in tools.items()},"working_directory":str(PROJECT_ROOT),"command":["/usr/bin/timeout","--signal=INT","--kill-after=30s","240s",PYTHON,"tools/v3/run_gse_relation_endpoint_episode_exposure_audit_v1.py","--spec",str(SPEC),"--run-dir",str(PROJECT_ROOT/f"results/gate3_semantics/{RUN_ID}")]}
 write_json(SPEC,spec);print(CARD.relative_to(PROJECT_ROOT));print(SPEC.relative_to(PROJECT_ROOT));return 0
if __name__=="__main__":raise SystemExit(main())
