#!/usr/bin/env python3
"""Freeze the causal episode class-mass audit card and run spec."""

from __future__ import annotations

from copy import deepcopy
import hashlib

from _bootstrap import PROJECT_ROOT
from mtare_topo.governance import load_json, write_json


RUN_ID = "gate3_20260827_gse_causal_episode_class_mass_audit_v1_seed0"
CARD = PROJECT_ROOT / "configs/v3/gate3/data_cards/gse_causal_episode_class_mass_audit_v1.json"
SPEC = PROJECT_ROOT / "configs/v3/gate3/gse_causal_episode_class_mass_audit_v1.json"
SOURCE_CARD = PROJECT_ROOT / "configs/v3/gate3/data_cards/gse_causal_episode_training_v1r.json"
TRAINING = "results/gate3_semantics/gate3_20260827_gse_causal_episode_training_v1r_seed0"
TEACHER = "results/gate2_representation/gate2_20260827_gse_corrected_causal_teacher_manifest_v1r_seed0"
VERIFIER = "results/gate3_semantics/gate3_20260826_gse_exit_token_association_corrective_v2_seed0"
RISK = "results/gate3_semantics/gate3_20260827_gse_causal_geometry_risk_conflict_audit_v1_seed0"
PYTHON = "/home/zeng-workstation/.local/share/mtare_topo_comm/envs/phase3_torch290_cu129_zarr2187_v1/bin/python"


def _sha(path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(4 * 1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def main() -> int:
    card = deepcopy(load_json(SOURCE_CARD))
    card.update({
        "card_id": "gse_causal_episode_class_mass_audit_v1",
        "status": "APPROVED_FOR_ONE_IMMUTABLE_GSE_CAUSAL_EPISODE_CLASS_MASS_AUDIT_V1",
        "purpose": "Measure whether raw episode-frequency MIL suppresses rare turn/transition loss and analytic logit-gradient mass in the sealed twelve-frame detector.",
    })
    card["approval"] = {
        "status": "APPROVED", "approved_by": "user", "approved_at": "2026-08-27T20:00:00+08:00",
        "authorized_operations": ["training"], "authorized_gates": [3],
        "scope": "One read-only C01-C08 analytic loss/gradient-mass audit of the sealed V1R outputs; zero model inference, optimization, threshold change or forbidden-world read.",
        "confirmation_reference": "User instructed Codex to automatically choose the evidence-supported best in-scope route without routine approval prompts.",
    }
    card["methods"] = {
        "main": "For every selection episode and seed/ensemble, select the MIL-max true-class row and analytically compute joint loss plus structural/conditional logit gradients from sealed probabilities. Compare raw episode-frequency mass with equal-class mass.",
        "baseline": "Raw fit episode distribution 2542/740/560/114 and the sealed V1R rare-class failure; lag10 frozen geometry-risk AUC 0.764515 is retained as independent observability evidence.",
        "fallback": "If rare-class suppression is not material, stop the detector route. If confirmed, authorize only a same-capacity equal-class MIL proposal; this audit performs no training.",
    }
    card["estimated_cost"] = {"compute": "CPU-only analytic audit", "disk_gb": .05, "host_ram_gb": 4, "gpu_memory_gb": 0, "wall_time_hours": .1}
    card["retention"] = "Retain analytic per-class mass metrics, config, raw log, source integrity, RUN_STATE and seal; no model or cache is created."
    card["evidence"] = {
        "machine_metrics": "Exact fit/selection episode counts, per-seed and ensemble loss/gradient mass, raw/equal-class multipliers, observability link, zero inference/optimization/forbidden reads and full seal.",
        "complete_visual_review": "No figure is generated by this bounded mechanism audit.",
        "failure_policy": "Any source/alignment/count drift, nonfinite probability, forbidden read or unmet hypothesis check seals FAIL; no silent adaptation.",
    }
    write_json(CARD, card)
    inputs = [
        f"{TRAINING}/RUN_STATE.json", f"{TRAINING}/metrics/summary.json", f"{TRAINING}/artifacts/evidence_sha256.txt",
        f"{TEACHER}/RUN_STATE.json", f"{TEACHER}/metrics/summary.json", f"{TEACHER}/artifacts/evidence_sha256.txt", f"{TEACHER}/artifacts/teacher_observations.jsonl",
        f"{VERIFIER}/RUN_STATE.json", f"{VERIFIER}/metrics/summary.json", f"{VERIFIER}/artifacts/evidence_sha256.txt", f"{VERIFIER}/artifacts/pair_cache/pairs.npz",
        f"{RISK}/RUN_STATE.json", f"{RISK}/metrics/summary.json", f"{RISK}/metrics/risk_conflict_summary.json", f"{RISK}/artifacts/evidence_sha256.txt",
    ]
    for seed in (0, 1, 2):
        inputs.append(f"{TRAINING}/artifacts/models/seed{seed}/selection_outputs.npz")
    tools = {
        "data_card": str(CARD.relative_to(PROJECT_ROOT)),
        "gradient_mass": "src/mtare_topo/evaluation/gse_episode_gradient_mass.py",
        "episode_reference": "src/mtare_topo/representation/gse_causal_episode_detector.py",
        "executor": "tools/v3/execute_gse_causal_episode_class_mass_audit_v1.py",
        "runner": "tools/v3/run_gse_causal_episode_class_mass_audit_v1.py",
        "freezer": "tools/v3/freeze_gse_causal_episode_class_mass_audit_spec_v1.py",
        "governance": "src/mtare_topo/governance.py", "preflight": "tools/v3/preflight.py", "create_run": "tools/v3/create_run.py",
    }
    spec = {
        "schema_version": "v3_run_spec_v1", "gate": 3, "execution_phase": 3,
        "date": "20260827", "slug": "gse_causal_episode_class_mass_audit_v1", "seed": 0,
        "operation": "audit",
        "question": "Did raw episode-frequency MIL suppress rare structural-class gradients despite observable longer-history geometry?",
        "method": card["methods"]["main"], "baseline": card["methods"]["baseline"], "fallback": card["methods"]["fallback"],
        "data_card": str(CARD.relative_to(PROJECT_ROOT)), "config_path": str(CARD.relative_to(PROJECT_ROOT)),
        "user_authorization": deepcopy(card["approval"]),
        "acceptance_criteria": [
            "Exact fit/selection episodes 3956/1350 with transition raw fit mass below 3% and equal-class multiplier above 8x.",
            "Ensemble raw transition gradient mass remains below junction while sealed lag10 frozen geometry-risk AUC remains at least 0.75.",
            "Zero inference, optimizer, C09/C10/strict/M-TARE reads; source unchanged and complete seal.",
        ],
        "expected_counts": {"fit_observations": 142184, "selection_observations": 45942, "fit_episodes": 3956, "selection_episodes": 1350, "optimizer_steps": 0, "model_inference_frames": 0, "c09_worlds_read": 0, "strict_test_worlds_read": 0, "mtare_worlds_read": 0},
        "expected_evidence": ["Per-class raw/equal objective mass and analytic gradient statistics for three seeds and ensemble, input hashes, log, RUN_STATE and seal."],
        "estimated_cost": {"compute": "CPU-only analytic audit", "disk_gb": .05, "wall_time_hours": .1},
        "frozen_inputs": {path: _sha(PROJECT_ROOT / path) for path in inputs},
        "frozen_tools": {name: {"path": path, "sha256": _sha(PROJECT_ROOT / path)} for name, path in tools.items()},
        "working_directory": str(PROJECT_ROOT),
        "command": [
            "/usr/bin/timeout", "--signal=INT", "--kill-after=30s", "600s", PYTHON,
            "tools/v3/run_gse_causal_episode_class_mass_audit_v1.py", "--spec", str(SPEC),
            "--run-dir", str(PROJECT_ROOT / "results/gate3_semantics" / RUN_ID),
        ],
    }
    write_json(SPEC, spec)
    print(CARD.relative_to(PROJECT_ROOT)); print(SPEC.relative_to(PROJECT_ROOT))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
