#!/usr/bin/env python3
"""Freeze causal circular exit-set process three-seed training spec."""
from __future__ import annotations
import hashlib
from _bootstrap import PROJECT_ROOT
from mtare_topo.governance import load_json,validate_data_card,write_json
RUN_ID="gate3_20260829_gse_circular_exit_set_process_three_seed_training_v1_seed0";SPEC=PROJECT_ROOT/"configs/v3/gate3/gse_circular_exit_set_process_three_seed_training_v1.json";DATA_CARD="configs/v3/gate3/data_cards/gse_circular_exit_set_process_three_seed_training_v1.json";PYTHON="/home/zeng-workstation/.local/share/mtare_topo_comm/envs/phase3_torch290_cu129_zarr2187_v1/bin/python"
def sha256(path):
 d=hashlib.sha256()
 with path.open("rb") as s:
  for b in iter(lambda:s.read(4*1024*1024),b""):d.update(b)
 return d.hexdigest()
def main():
 if SPEC.exists():raise RuntimeError("exit-set training spec exists")
 card=load_json(PROJECT_ROOT/DATA_CARD);v=validate_data_card(card)
 if not v.passed:raise RuntimeError(f"training card invalid:{v.errors}")
 dataset="results/gate2_representation/gate2_20260824_gse_deduplicated_dataset_export_v1_seed0";teacher="results/gate2_representation/gate2_20260829_gse_circular_exit_geometry_field_teacher_export_v1_seed0";readiness="results/gate3_semantics/gate3_20260829_gse_circular_exit_set_process_readiness_v1r_seed0";v2="results/gate3_semantics/gate3_20260829_gse_circular_peak_geometry_three_seed_training_v2_seed0"
 inputs=[DATA_CARD,f"{dataset}/RUN_STATE.json",f"{dataset}/metrics/summary.json",f"{dataset}/artifacts/shard_manifest.json",f"{dataset}/artifacts/evidence_sha256.txt",f"{teacher}/RUN_STATE.json",f"{teacher}/metrics/summary.json",f"{teacher}/artifacts/export/teacher_shard_manifest.jsonl",f"{teacher}/artifacts/evidence_sha256.txt",f"{readiness}/RUN_STATE.json",f"{readiness}/metrics/summary.json",f"{readiness}/artifacts/evidence_sha256.txt",f"{v2}/RUN_STATE.json",f"{v2}/metrics/summary.json",f"{v2}/artifacts/evidence_sha256.txt","configs/v3/gate2/environments/phase3_torch290_cu129_zarr2187_v1r2.json"]
 tools={"set_process":"src/mtare_topo/representation/gse_circular_exit_set_process.py","backbone":"src/mtare_topo/representation/gse_circular_peak_geometry_model.py","circular_layers":"src/mtare_topo/representation/phase3_structural_semantics.py","training_core":"tools/v3/train_gse_circular_peak_geometry_v1.py","trainer":"tools/v3/train_gse_circular_exit_set_process_v1.py","evaluator":"tools/v3/evaluate_gse_circular_exit_set_process_selection_v1.py","runner":"tools/v3/run_gse_circular_exit_set_process_three_seed_training_v1.py","freezer":"tools/v3/freeze_gse_circular_exit_set_process_three_seed_training_spec_v1.py","model_tests":"tests/v3/unit/test_gse_circular_exit_set_process.py","metric_tests":"tests/v3/unit/test_gse_circular_exit_set_process_metrics.py","governance":"src/mtare_topo/governance.py","preflight":"tools/v3/preflight.py","create_run":"tools/v3/create_run.py"}
 spec={"schema_version":"v3_run_spec_v1","gate":3,"execution_phase":3,"date":"20260829","slug":"gse_circular_exit_set_process_three_seed_training_v1","seed":0,"operation":"training","data_card":DATA_CARD,
 "question":"Can normalized circular finite-set likelihood plus explicit 1-4 cardinality learn safe continuous executable exit sets and full geometry on C07 and transfer once to C08?",
 "method":"Three from-scratch 769784-parameter seeds, 10 epochs, C07 total-loss checkpointing, probability-mean set/count ensemble and one C07 joint-confidence refusal threshold; no independent existence threshold.","baseline":"Frozen local-peak V2 strict AP 0.110522/0.097221 with no safe threshold and raw-range AP 0.051493.","fallback":"Any set safety, cardinality, exact-set or geometry failure seals FAIL before nodes/graph; no oracle count, wider matching, retry or planner compensation.","user_authorization":card["approval"],
 "acceptance_criteria":["Exactly 3 seeds x10 epochs x11370 steps from scratch; 769784 parameters and no class/loss weights.","C07-selected refusal at continuous one-to-one tolerance <=2 degrees gives exit precision>=0.995 and recall>=0.50 on C07/C08.","Raw count accuracy>=0.80, deployed action macro-F1>=0.80 and exact correct set fraction>=0.50 on both.","Bearing MAE<=1 degree, exit width<=3m, profile<=1m and all global geometry bounds including slope<=2 degrees.","C08 checkpoint observations zero; C09/C10/M-TARE/graph/planner zero; frozen inputs unchanged."],
 "expected_counts":{"fit_worlds":60,"c07_worlds":10,"c08_worlds":10,"fit_observations":142184,"c07_observations":21548,"c08_observations":24394,"fit_exits":299872,"c07_exits":45504,"c08_exits":51537,"parameters":769784,"seeds":3,"epochs_per_seed":10,"optimizer_steps_per_seed":11370,"optimizer_steps":34110,"c08_checkpoint_observations":0,"c09_worlds_read":0,"c10_worlds_read":0,"mtare_worlds_read":0,"graph_replays":0},
 "expected_evidence":["Three checkpoints/histories/summaries and compact set/count/geometric predictions.","C07 refusal selection, C08 transfer, continuous set/cardinality/action/geometry and per-world metrics.","PNG/PDF/SVG/source, environment, commands, raw logs, RUN_STATE and seal."],"estimated_cost":{"compute":"Three sequential CUDA trainings and development evaluation","wall_time_hours":3,"host_ram_gb":16,"gpu_memory_gb":16,"disk_gb":2,"gpu":"one NVIDIA GeForce RTX 5090 D"},
 "frozen_inputs":{p:sha256(PROJECT_ROOT/p) for p in sorted(inputs)},"frozen_tools":{n:{"path":p,"sha256":sha256(PROJECT_ROOT/p)} for n,p in tools.items()},"working_directory":str(PROJECT_ROOT),"command":["/usr/bin/timeout","86400s",PYTHON,"tools/v3/run_gse_circular_exit_set_process_three_seed_training_v1.py","--spec",str(SPEC),"--run-dir",str(PROJECT_ROOT/f"results/gate3_semantics/{RUN_ID}")]}
 write_json(SPEC,spec);print(SPEC.relative_to(PROJECT_ROOT));return 0
if __name__=="__main__":raise SystemExit(main())
