const {test}=require('node:test');
const assert=require('node:assert/strict');
const {BrowserReview,validateBundle,validateAnnotation,emptyAnnotation}=require('../../../tools/v3/review/gse_structure_review.js');
function bundle(){return {schema:'gse_structure_blind_bundle_v1',bundle_id:'anonymous',coordinate_frame:'current_sensor_m',decisions:Array.from({length:21},(_,i)=>({decision_index:i,source_frame_keys:Array.from({length:5},(_,j)=>'f'+(i+j)),source_order_indices:Array.from({length:5},(_,j)=>i+j),points_xyz_m:[[0,0,1]]}))};}
test('blind-before-reference and no backfill',()=>{const b=bundle(),s=new BrowserReview(b,'a'.repeat(64),'reviewer');const r={schema:'gse_structure_reference_v1',bundle_id:'anonymous',decisions:b.decisions.map(d=>({decision_index:d.decision_index,reference_annotation:emptyAnnotation()}))};assert.throws(()=>s.reveal(r,'b'));for(let i=0;i<21;i++)s.commit(i,emptyAnnotation());const before=s.export().blind_records;s.reveal(r,'b');s.finish('checked');assert.deepEqual(s.export().blind_records,before);assert.throws(()=>s.commit(0,emptyAnnotation()));assert.throws(()=>s.finish('edit'));assert.equal(s.export().automatic_training_eligibility,false);});
test('source reverse and identity drift rejected',()=>{const b=bundle();b.decisions[2].source_order_indices=[0,1,2,3,4];assert.throws(()=>validateBundle(b));const c=bundle();c.decisions[1].source_frame_keys[0]='other';assert.throws(()=>validateBundle(c));});
test('bad annotation never locks a decision',()=>{const s=new BrowserReview(bundle(),'a','reviewer');const a=emptyAnnotation();a.complete_regions=[{min_xyz_m:[null,null,null],max_xyz_m:[null,null,null],reason:'template'}];assert.throws(()=>s.commit(0,a));assert.equal(s.current().decision_index,0);});
test('unknown dimensions stay null',()=>{const a=emptyAnnotation();a.structures=[{local_id:0,event:'junction',center_xyz_m:null,evidence_note:'visible',openings:[{position_xyz_m:null,direction:null,width_m:null,height_m:null,evidence_note:'visible direction'}]}];validateAnnotation(a);assert.equal(a.structures[0].openings[0].width_m,null);});
test('caller cannot mutate committed observations',()=>{const b=bundle(),s=new BrowserReview(b,'a','reviewer');b.decisions[0].points_xyz_m[0][2]=999;assert.equal(s.current().points_xyz_m[0][2],1);const a=emptyAnnotation();s.commit(0,a);a.notes='future';assert.equal(s.export().blind_records[0].annotation.notes,'');});
