"""Synthetic segment boundaries, not real registration or deployment evidence."""
from copy import deepcopy

import pytest

from mtare_topo.topology.gse_causal_graph import StructuralPort
from mtare_topo.topology.gse_segmented_graph_v1 import (
    SegmentedCausalStructuralGraph, SegmentCoordinate, SegmentPose,
    SegmentObservation, SegmentAssociationEvidence,
)


PORT = StructuralPort(0, (1., 0., 0.), 2., 3., .99)


def graph(stable_frames=1):
    return SegmentedCausalStructuralGraph(stable_frames=stable_frames,
        event_confidence=.8, maximum_uncertainty=.2)


def observe(g, i, x, event="junction", *, candidates=(), continuous=True, kind="order_index"):
    return g.update(SegmentObservation(event, .99, .01, (PORT,)),
        SegmentPose((float(x), 0., 0.), (.01, .01, .01)), coordinate=SegmentCoordinate(kind, i),
        candidates=candidates, continuous=continuous)


def abc(g):
    g.begin_segment("first", coordinate_kind="order_index")
    observe(g, 0, 0)
    g.depart(0)
    observe(g, 1, 3, "corridor")
    observe(g, 2, 10)
    g.depart(0)
    observe(g, 3, 14, "corridor")
    observe(g, 4, 20)


def test_abc_preserves_intermediate_node_and_both_completed_edges():
    g = graph(); abc(g)
    state = g.snapshot()
    assert len(state["nodes"]) == 3
    assert [(e["source_node"], e["target_node"], e["length_m"]) for e in state["edges"]] == [(0, 1, 10.), (1, 2, 10.)]
    assert [[p["coordinate"]["value"] for p in e["poses"]] for e in state["edges"]] == [[0, 1, 2], [2, 3, 4]]
    assert [e["trace_id"] for e in state["edges"]] == [0, 1]
    assert all(e["segment_id"] == "first" for e in state["edges"])


def test_end_abandons_unfinished_departure_and_never_connects_next_segment():
    g = graph(); g.begin_segment("a", coordinate_kind="order_index")
    observe(g, 0, 0); g.depart(0); observe(g, 1, 2, "corridor")
    ended = g.end_segment()
    assert ended["abandoned_departure"]["reason"] == "SEGMENT_ENDED_BEFORE_ARRIVAL"
    assert len(ended["abandoned_departure"]["poses"]) == 2
    g.begin_segment("b", coordinate_kind="order_index")
    with pytest.raises(ValueError, match="departure requires"):
        g.depart(0)
    observe(g, 0, 100)
    assert len(g.snapshot()["nodes"]) == 2 and not g.snapshot()["edges"]
    g.depart(0); observe(g, 1, 103, "corridor"); observe(g, 2, 110)
    edge = g.snapshot()["edges"][0]
    assert edge["source_node"] == 1 and edge["target_node"] == 2 and edge["trace_id"] == 1
    assert edge["length_m"] == 10 and edge["segment_id"] == "b"


def test_segment_reset_preserves_traversed_ports_even_interrupted_repeat_attempt():
    g = graph(); abc(g); g.end_segment()
    g.begin_segment("revisit", coordinate_kind="order_index")
    # Explicit synthetic verifier fixture; no registration generated by wrapper.
    evidence = SegmentAssociationEvidence(1, "revisit", SegmentCoordinate("order_index", 0), True, True, True, True)
    result = observe(g, 0, 10, candidates=(evidence,))
    assert result["action"] == "verified_revisit" and result["node_id"] == 1
    assert g.snapshot()["nodes"][1]["port_states"][0] == "traversed"
    g.depart(0)
    assert g.snapshot()["nodes"][1]["port_states"][0] == "traversed"
    observe(g, 1, 12, "corridor"); g.end_segment()
    g.begin_segment("third", coordinate_kind="order_index")
    assert g.snapshot()["nodes"][1]["port_states"][0] == "traversed"
    assert len(g.snapshot()["edges"]) == 2


def test_event_streak_and_episode_are_cleared_at_boundary():
    g = graph(stable_frames=2); g.begin_segment("a", coordinate_kind="order_index")
    assert observe(g, 0, 0)["action"] == "event_pending"
    g.end_segment(); g.begin_segment("b", coordinate_kind="order_index")
    assert observe(g, 0, 10)["action"] == "event_pending"
    assert observe(g, 1, 10)["action"] == "local_confirmed"
    g.end_segment(); g.begin_segment("c", coordinate_kind="order_index")
    assert observe(g, 0, 20)["action"] == "event_pending"
    assert observe(g, 1, 20)["action"] == "local_confirmed"
    assert len(g.snapshot()["nodes"]) == 2 and not g.snapshot()["edges"]


def test_snapshot_and_immutable_trace_prefix_do_not_change_with_future():
    short = graph(); short.begin_segment("a", coordinate_kind="order_index")
    observe(short, 0, 0); short.depart(0); observe(short, 1, 5, "corridor")
    prefix = short.snapshot(); frozen = deepcopy(prefix); trace = short.immutable_trace
    full = graph(); full.begin_segment("a", coordinate_kind="order_index")
    observe(full, 0, 0); full.depart(0); observe(full, 1, 5, "corridor")
    assert full.snapshot() == prefix
    observe(full, 2, 10); full.end_segment()
    assert full.immutable_trace[:len(trace)] == trace and prefix == frozen
    prefix["nodes"][0]["port_states"][0] = "external_corruption"
    assert short.snapshot()["nodes"][0]["port_states"][0] == "attempted"


@pytest.mark.parametrize("kind,first,invalid", [("order_index", 3, 2), ("order_index", 3, 3),
    ("seconds", 2.1, 2.), ("seconds", 2.1, 2.1)])
def test_backwards_or_duplicate_coordinate_rejected_without_mutation(kind, first, invalid):
    g = graph(); g.begin_segment("a", coordinate_kind=kind); observe(g, first, 0, kind=kind)
    old = g.snapshot()
    with pytest.raises(ValueError, match="increase strictly"):
        observe(g, invalid, 1, kind=kind)
    assert old == g.snapshot()


def test_wrong_kind_and_stale_association_rejected_without_mutation():
    g = graph(); g.begin_segment("a", coordinate_kind="order_index"); observe(g, 0, 0)
    old = g.snapshot()
    with pytest.raises(ValueError, match="kind differs"):
        observe(g, 1., 1, kind="seconds")
    evidence = SegmentAssociationEvidence(0, "other", SegmentCoordinate("order_index", 1), True, True, True, True)
    with pytest.raises(ValueError, match="stale/wrong"):
        observe(g, 1, 1, candidates=(evidence,))
    assert old == g.snapshot()


def test_no_implicit_association_at_same_position_across_segments():
    g = graph(); g.begin_segment("a", coordinate_kind="order_index"); observe(g, 0, 0); g.end_segment()
    g.begin_segment("b", coordinate_kind="order_index")
    assert observe(g, 0, 0)["action"] == "local_confirmed"
    assert len(g.snapshot()["nodes"]) == 2


def test_discontinuous_trace_is_not_completed_even_inside_one_segment():
    g = graph(); g.begin_segment("a", coordinate_kind="order_index"); observe(g, 0, 0); g.depart(0)
    observe(g, 1, 5, "corridor", continuous=False)
    assert observe(g, 2, 10)["action"].endswith("trace_rejected")
    assert not g.snapshot()["edges"]


def test_lifecycle_failures_and_duplicate_ids():
    g = graph()
    for operation in (lambda: observe(g, 0, 0), lambda: g.depart(0), g.end_segment):
        with pytest.raises(ValueError, match="begin_segment"): operation()
    g.begin_segment("a", coordinate_kind="order_index")
    with pytest.raises(ValueError, match="end the active"): g.begin_segment("b", coordinate_kind="seconds")
    g.end_segment()
    with pytest.raises(ValueError, match="never reused"): g.begin_segment("a", coordinate_kind="order_index")


def test_all_exported_pose_and_decision_coordinates_explicit_no_fake_seconds():
    g = graph(); abc(g); g.end_segment()
    def inspect(value):
        if isinstance(value, dict):
            assert "timestamp_s" not in value and "duration_s" not in value
            for nested in value.values(): inspect(nested)
        elif isinstance(value, (tuple, list)):
            for nested in value: inspect(nested)
    state = g.snapshot(); inspect(state)
    assert state["legacy_clock_adapter"] == "PRIVATE_CALL_ORDINAL_NOT_SECONDS"
    assert state["time_metrics_available"] is False
    assert state["nodes"][0]["pose"]["coordinate"] == {"segment_id": "first", "kind": "order_index", "value": 0}
    s = graph(); s.begin_segment("seconds", coordinate_kind="seconds"); observe(s, 12.5, 0, kind="seconds")
    assert s.snapshot()["nodes"][0]["pose"]["coordinate"]["value"] == 12.5


@pytest.mark.parametrize("kind,value", [("order_index", True), ("order_index", 1.), ("order_index", -1),
                                       ("seconds", True), ("seconds", float("nan")), ("frame", 0)])
def test_invalid_coordinates(kind, value):
    with pytest.raises(ValueError): SegmentCoordinate(kind, value)


def test_caller_mutation_of_pose_cannot_rewrite_stored_edge_trace():
    g = graph(); g.begin_segment("a", coordinate_kind="order_index")
    xyz = [0., 0., 0.]
    g.update(SegmentObservation("junction", .99, .01, (PORT,)), SegmentPose(xyz, [.01] * 3),
             coordinate=SegmentCoordinate("order_index", 0))
    g.depart(0); xyz[0] = 1000
    observe(g, 1, 5, "corridor"); observe(g, 2, 10)
    assert g.snapshot()["edges"][0]["length_m"] == 10
